### ISSUE TITLE
Using /spawn in other dimensions

### ISSUE THREAD

**Issue by Mappy264** [montlikadani/SetTheSpawn#14]
### Problem
When you use /spawn in any world that isn't the overworld you get teleported to the same location just in the dimension you used it in. I don't know if this intentional but it definitely was a surprise when my players lost their items. 
### Details
Plugin version: 
SetTheSpawn v2.6.5
Software version: 
Spigot
Relevant plugins: 

### Configuration file(s)

config.yml: 
https://pastebin.com/q0en4Tfz

**Comment by montlikadani** [comment]
List out all your plugins.

**Comment by montlikadani** [comment]
Fixed in the latest versions.
