### ISSUE TITLE
Can't seem to disable money

### ISSUE THREAD

**Issue by Crux-Ansata** [montlikadani/SetTheSpawn#15]
I am looking to disable any money transactions to use /spawn.

`# Cost for /spawn command executing or sign interacting.
# For this, requires the Vault plugin.
spawn-cost:
  enable: false`

This doesn't seem to do the trick and I have tried disabling other things, hoping to fix it but cannot seem to. This only started happening after updating.

**Comment by montlikadani** [comment]
You should set the `cost` amount to 0
