### ISSUE TITLE
An internal error occurred while attempting to perform command /spawn.

### ISSUE THREAD

**Issue by Crux-Ansata** [montlikadani/SetTheSpawn#16]
Worked fine yesterday, today I got this error:

`13.02 11:53:59 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'setspawn' in plugin SetTheSpawn v2.6.7
13.02 11:53:59 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.16.5.jar:git-Paper-428]
13.02 11:53:59 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.5.jar:git-Paper-428]
13.02 11:53:59 [Server] INFO at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:807) ~[patched_1.16.5.jar:git-Paper-428]
13.02 11:53:59 [Server] INFO at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:2021) ~[patched_1.16.5.jar:git-Paper-428]
13.02 11:53:59 [Server] INFO at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:1832) ~[patched_1.16.5.jar:git-Paper-428]
13.02 11:53:59 [Server] INFO at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1785) ~[patched_1.16.5.jar:git-Paper-428]
13.02 11:53:59 [Server] INFO at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.16.5.jar:git-Paper-428]
13.02 11:53:59 [Server] INFO at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.16.5.jar:git-Paper-428]
13.02 11:53:59 [Server] INFO at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.5.jar:git-Paper-428]
13.02 11:53:59 [Server] INFO at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Paper-428]
13.02 11:53:59 [Server] INFO at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Paper-428]
13.02 11:53:59 [Server] INFO at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Paper-428]
13.02 11:53:59 [Server] INFO at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Paper-428]
13.02 11:53:59 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1132) ~[patched_1.16.5.jar:git-Paper-428]
13.02 11:53:59 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1125) ~[patched_1.16.5.jar:git-Paper-428]
13.02 11:53:59 [Server] INFO at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Paper-428]
13.02 11:53:59 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1086) ~[patched_1.16.5.jar:git-Paper-428]
13.02 11:53:59 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1000) ~[patched_1.16.5.jar:git-Paper-428]
13.02 11:53:59 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:173) ~[patched_1.16.5.jar:git-Paper-428]
13.02 11:53:59 [Server] INFO at java.lang.Thread.run(Thread.java:834) [?:?]
13.02 11:53:59 [Server] INFO Caused by: java.lang.NullPointerException
13.02 11:53:59 [Server] INFO at hu.montlikadani.setthespawn.SpawnHandler.setSpawn(SpawnHandler.java:115) ~[?:?]
13.02 11:53:59 [Server] INFO at hu.montlikadani.setthespawn.SpawnHandler.setSpawn(SpawnHandler.java:71) ~[?:?]
13.02 11:53:59 [Server] INFO at hu.montlikadani.setthespawn.SpawnHandler.setSpawn(SpawnHandler.java:47) ~[?:?]
13.02 11:53:59 [Server] INFO at hu.montlikadani.setthespawn.commands.SetSpawn.onCommand(SetSpawn.java:66) ~[?:?]
13.02 11:53:59 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.16.5.jar:git-Paper-428]
13.02 11:53:59 [Server] INFO ... 19 more`

### Details
Plugin version: v2.6.7

**Comment by montlikadani** [comment]
You successfully manager to delete the `spawns.yml` file and you performed delete spawn.

**Comment by Crux-Ansata** [comment]
```
spawns:
  world: kingsandqueens
  x: -36.471924637897864
  y: 18.0
  z: -165.46304317890412
  yaw: -1.1191034
  pitch: -3.734734

```

This is the spawns.yml, it is still there and still states the spawn we have set it up for. (which worked before)

**Comment by montlikadani** [comment]
Should works in the latest release
