### ISSUE TITLE
when i go to spawn i spawn underground

### ISSUE THREAD

**Issue by Allualbert** [montlikadani/SetTheSpawn#17]
### Problem
when i go to spawn i spawn underground 
the spawn is set to somewhere else up
### Details
Plugin version: 
2.6.8

Software version: 
git paper 331

Relevant plugins: 

### Console error
```
Send the console error if you have it.
```

### Configuration file(s)

config.yml: 
https://pastebin.com/EL1Vt4S6

**Comment by montlikadani** [comment]
When i go to spawn.. i spawn underground... More informations please? Maybe how to reproduce, plugin version etc. I don't know what should I do with this issue.

**Comment by Allualbert** [comment]
edited and sorry

**Comment by montlikadani** [comment]
Send your spawns.yml file

**Comment by Allualbert** [comment]
spawns:
  world: world
  x: -42.5
  y: 191.0
  z: 62.5
  yaw: 223.97084
  pitch: 90.0

**Comment by Allualbert** [comment]
it teleports the player to 0 0 0

**Comment by montlikadani** [comment]
I don't know how to reproduce this, because for me works as intended. Maybe at your xyz location the chunks are unloaded/removed?

**Comment by Allualbert** [comment]
shouldn't be

**Comment by montlikadani** [comment]
Is this still reproducible in the new release? v2.6.9
