### ISSUE TITLE
Last location

### ISSUE THREAD

**Issue by Deeptanil** [montlikadani/SetTheSpawn#19]
This is a great plugin! Only thing I rely want in it is,

Last location, i know multiverse inventory has this feature, but I'm having a issue.
When a player enters another dimension, and dies there, they get teleported to the last location in the over world. Aka, at the portal. Which is instantly teleported them into the same dimension.
So I want them to be teleported to Spawn, or spawn bed/anchor.
Can u implement this into you're plugin?? Also add to we can disable worlds where we don't want last location. Would be great if you can do this by 23rd Aug :D 

Thanks, Deeptanil.

**Comment by montlikadani** [comment]
Last location? It is mostly used in essentials and multiverse, it cannot be handled in this plugin.

**Comment by Deeptanil** [comment]
So right now, I've a Lobby, from lobby they are mvtp-ed to Survival world. But they are sent to spawn.

And with multiverse last_location, they are sent right into the portal (as I said in the original post)

**Comment by montlikadani** [comment]
Essentials is the only one which provides last location, and this is the `back` command.

**Comment by Deeptanil** [comment]
Alright thanks for you're time.
