### ISSUE TITLE
custom message times

### ISSUE THREAD

**Issue by Fireeyeeian** [montlikadani/SetTheSpawn#7]
It would be nice if this plugin allowed for configuration of how long the messages stay on screen. For example the re-spawn message; saying how many blocks away you re-spawned.

**Comment by montlikadani** [comment]
> re-spawn message; saying how many blocks away you re-spawned.

From where the player respawned?

> It would be nice if this plugin allowed for configuration of how long the messages stay on screen.

This can be configured in the titles section.

**Comment by Fireeyeeian** [comment]
I'll take a look when I get a chance. I must've missed it.
