### ISSUE TITLE
Interference with queue  

### ISSUE THREAD

**Issue by Temp63Person** [montlikadani/SetTheSpawn#8]
Im using a queue plugin called Simple-queue https://www.spigotmc.org/resources/simplequeue.43115/
While it is meant for 1.12 i have been using it on 1.15.2 with no problem, until i decided to use in on my main server which has your plugin setthespawn, the queue system is suppose to work when players are in the log in screen, however you plugin simply makes it say "server is full!" i assumed this was a simple text thing i could delete in the config, however i have not found it, any help would be much appreciated.

**Comment by montlikadani** [comment]
The SetTheSpawn plugin not handles the player login event. You should report to the SimpleQueue plugin developer.
