### ISSUE TITLE
Per world spawn not working.

### ISSUE THREAD

**Issue by WolfyGamingWorld** [montlikadani/SetTheSpawn#9]
### Problem

The spawn doesn't work properly and teleports me to another world spawn when I'm in another world. Like from World B which has a set spawn already, teleports me to world A's spawn.

### Details
Plugin version: 2.6.2

Software version: Spigot-dcd1643-e60fc34 1.12.2

Relevant plugins: Multiverse Core, Inventories and Portals.

### Console error
```
No error in console.
```

### Configuration file(s)

config.yml: https://pastebin.com/u8PQ6p3F

**Comment by montlikadani** [comment]
Should works in the latest version.
